OrdererOrgs:
- Name: Orderer
  Domain: example.com
  Specs:
  - Hostname: orderer0
PeerOrgs:
- Name: Org1
  Domain: org1.example.com
  Template:
    Count: 1
  Users:
    Count: 1
- Name: Org2
  Domain: org2.example.com
  Template:
    Count: 1
  Users:
    Count: 1
