---
test:
  name: Composer Performance test
  description: This is an example Composer perf test
  clients:
    type: local
    number: 2
  rounds:
  - label: basic-sample-network
    txNumber:
    - 25
    trim: 0
    rateControl:
    - type: fixed-rate
      opts:
        tps: 5
    arguments:
      testAssets: 25
    callback: benchmark/composer/composer-samples/basic-sample-network.js
  - label: basic-sample-network
    txNumber:
    - 50
    trim: 0
    rateControl:
    - type: pid-rate
      opts:
        targetLoad: 5
        initialTPS: 2
        proportional: 0.2
        integral: 0.0001
        derrivative: 0.1
    arguments:
      testAssets: 50
    callback: benchmark/composer/composer-samples/basic-sample-network.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1