---
test:
  name: smallbank
  description: This is smallbank benchmark for caliper
  clients:
    type: local
    number: 5
  rounds:
  - label: smallOperations
    txDuration:
    - 3600
    rateControl:
    - type: fixed-rate
      opts:
        tps: 300
    arguments:
      accounts: 60000
      txnPerBatch: 1
    callback: benchmark/smallbank/smallbankOperations.js
  - label: query
    txNumber:
    - 5000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 500
    callback: benchmark/smallbank/query.js
monitor:
  type: docker
  docker:
    name:
    - all
  interval: 1
