---
test:
  name: smallbank
  description: This is smallbank benchmark for caliper
  clients:
    type: local
    number: 5
  rounds:
  - label: smallOperations
    txNumber:
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 100
    - type: fixed-rate
      opts:
        tps: 200
    - type: fixed-rate
      opts:
        tps: 300
    - type: fixed-rate
      opts:
        tps: 400
    - type: fixed-rate
      opts:
        tps: 500
    - type: fixed-rate
      opts:
        tps: 600
    - type: fixed-rate
      opts:
        tps: 700
    - type: fixed-rate
      opts:
        tps: 800
    - type: fixed-rate
      opts:
        tps: 900
    - type: fixed-rate
      opts:
        tps: 1000
    - type: fixed-rate
      opts:
        tps: 1100
    - type: fixed-rate
      opts:
        tps: 1200
    - type: fixed-rate
      opts:
        tps: 1300
    - type: fixed-rate
      opts:
        tps: 1400
    - type: fixed-rate
      opts:
        tps: 1500
    - type: fixed-rate
      opts:
        tps: 1600
    - type: fixed-rate
      opts:
        tps: 1700
    - type: fixed-rate
      opts:
        tps: 1800
    - type: fixed-rate
      opts:
        tps: 1900
    - type: fixed-rate
      opts:
        tps: 2000
    arguments:
      accounts: 50000
      txnPerBatch: 1
    callback: benchmark/smallbank/smallbankOperations.js
  - label: query
    txNumber:
    - 500
    rateControl:
    - type: fixed-rate
      opts:
        tps: 50
    callback: benchmark/smallbank/query.js
monitor:
  type: docker
  docker:
    name:
    - all
  interval: 1
