---
test:
  name: smallbank
  description: Caliper Experiments Increasing rate r * numClients
  clients:
    type: zookeeper
    zoo:
      server: 10.0.0.25:2181
      clientsPerHost: 1
  rounds:
  - label: smallOperations
    txDuration:
    - 120
    - 120
    - 120
    - 120
    - 120
    - 120
    rateControl:
    - type: fixed-rate
      opts:
        tps: 100
    - type: fixed-rate
      opts:
        tps: 200
    - type: fixed-rate
      opts:
        tps: 400
    - type: fixed-rate
      opts:
        tps: 600
    - type: fixed-rate
      opts:
        tps: 800
    - type: fixed-rate
      opts:
        tps: 1000
    arguments:
      accounts: 60000
      txnPerBatch: 1
    callback: benchmark/smallbank/smallbankOperations.js
  - label: query
    txNumber:
    - 5000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 500
    callback: benchmark/smallbank/query.js
monitor:
  type: docker
  docker:
    name:
    - all
  interval: 1
