---
test:
  name: simple
  description: This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  clients:
    type: local
    number: 4
  rounds:
  - label: open
    txMode:
      type: file-write
    txNumber:
    - 4000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 4000
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
