OrdererOrgs:
- Name: Orderer
  Domain: example.com
  Specs:
  - Hostname: orderer
PeerOrgs:
- Name: Org1
  Domain: org1.example.com
  Template:
    Count: 1
  Users:
    Count: 1
- Name: Org2
  Domain: org2.example.com
  Template:
    Count: 1
  Users:
    Count: 1
- Name: Org3
  Domain: org3.example.com
  Template:
    Count: 1
  Users:
    Count: 1
- Name: Org4
  Domain: org4.example.com
  Template:
    Count: 1
  Users:
    Count: 1
- Name: Org5
  Domain: org5.example.com
  Template:
    Count: 1
  Users:
    Count: 1
- Name: Org6
  Domain: org6.example.com
  Template:
    Count: 1
  Users:
    Count: 1
- Name: Org7
  Domain: org7.example.com
  Template:
    Count: 1
  Users:
    Count: 1
- Name: Org8
  Domain: org8.example.com
  Template:
    Count: 1
  Users:
    Count: 1
- Name: Org9
  Domain: org9.example.com
  Template:
    Count: 1
  Users:
    Count: 1
- Name: Org10
  Domain: org10.example.com
  Template:
    Count: 1
  Users:
    Count: 1
- Name: Org11
  Domain: org11.example.com
  Template:
    Count: 1
  Users:
    Count: 1
- Name: Org12
  Domain: org12.example.com
  Template:
    Count: 1
  Users:
    Count: 1
- Name: Org13
  Domain: org13.example.com
  Template:
    Count: 1
  Users:
    Count: 1
- Name: Org14
  Domain: org14.example.com
  Template:
    Count: 1
  Users:
    Count: 1
- Name: Org15
  Domain: org15.example.com
  Template:
    Count: 1
  Users:
    Count: 1
- Name: Org16
  Domain: org16.example.com
  Template:
    Count: 1
  Users:
    Count: 1
